apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-storage
  namespace: hadoop
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi